// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WormBook.Models;

#nullable disable

namespace WormBook.Migrations
{
    [DbContext(typeof(MiContexto))]
    partial class MiContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("CLIENTE_SEQ");

            modelBuilder.HasSequence("ENVIO_SEQ");

            modelBuilder.HasSequence("PEDIDOESPECIAL_SEQ");

            modelBuilder.HasSequence("PRODUCTO_SEQ");

            modelBuilder.HasSequence("REPOPEDIDO_SEQ");

            modelBuilder.HasSequence("SUCURSAL_SEQ");

            modelBuilder.HasSequence("VENTA_SEQ");

            modelBuilder.Entity("WormBook.Models.Cliente", b =>
                {
                    b.Property<int>("Idcliente")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDCLIENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("APELLIDO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TELEFONO");

                    b.HasKey("Idcliente");

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Envio", b =>
                {
                    b.Property<int>("Guiaenvio")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GUIAENVIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Guiaenvio"));

                    b.Property<int>("Numcajas")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMCAJAS");

                    b.Property<int>("Sucursaldestino")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUCURSALDESTINO");

                    b.Property<int>("Sucursalorigen")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUCURSALORIGEN");

                    b.HasKey("Guiaenvio");

                    b.HasIndex("Sucursaldestino");

                    b.HasIndex("Sucursalorigen");

                    b.ToTable("ENVIO", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Existencium", b =>
                {
                    b.Property<int>("CodigoInterno")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    b.Property<int>("Codigosucursal")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOSUCURSAL");

                    b.Property<int>("Existencia")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EXISTENCIA");

                    b.HasKey("CodigoInterno", "Codigosucursal");

                    b.HasIndex("Codigosucursal");

                    b.ToTable("EXISTENCIA", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Juegomesa", b =>
                {
                    b.Property<int>("Codigointerno")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("URL");

                    b.HasKey("Codigointerno");

                    b.ToTable("JUEGOMESA", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Libro", b =>
                {
                    b.Property<int>("CodigoInterno")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("AUTOR");

                    b.Property<string>("Editorial")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("EDITORIAL");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TITULO");

                    b.HasKey("CodigoInterno");

                    b.ToTable("LIBRO", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Pedidoespecial", b =>
                {
                    b.Property<int>("Numpedido")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMPEDIDO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numpedido"));

                    b.Property<int>("Cantidadpedida")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CANTIDADPEDIDA");

                    b.Property<int>("CodigoInterno")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    b.Property<int>("Codigosucursal")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOSUCURSAL");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("Fechapedido")
                        .HasColumnType("DATE")
                        .HasColumnName("FECHAPEDIDO");

                    b.Property<int>("Idcliente")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDCLIENTE");

                    b.HasKey("Numpedido");

                    b.HasIndex("CodigoInterno");

                    b.HasIndex("Codigosucursal");

                    b.HasIndex("Idcliente");

                    b.ToTable("PEDIDOESPECIAL", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.ProductPriv", b =>
                {
                    b.Property<string>("Attribute")
                        .HasMaxLength(240)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(240)")
                        .HasColumnName("ATTRIBUTE");

                    b.Property<string>("CharValue")
                        .HasMaxLength(240)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(240)")
                        .HasColumnName("CHAR_VALUE");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("DATE")
                        .HasColumnName("DATE_VALUE");

                    b.Property<string>("LongValue")
                        .HasColumnType("LONG")
                        .HasColumnName("LONG_VALUE");

                    b.Property<decimal?>("NumericValue")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("NUMERIC_VALUE");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("PRODUCT");

                    b.Property<string>("Scope")
                        .HasMaxLength(240)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(240)")
                        .HasColumnName("SCOPE");

                    b.Property<string>("Userid")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("USERID");

                    b.ToTable((string)null);

                    b.ToView("PRODUCT_PRIVS", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Producto", b =>
                {
                    b.Property<int>("CodigoInterno")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoInterno"));

                    b.Property<string>("Codigobarras")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("CODIGOBARRAS");

                    b.Property<int?>("Precio")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRECIO");

                    b.HasKey("CodigoInterno");

                    b.ToTable("PRODUCTO", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Productosenviado", b =>
                {
                    b.Property<int>("CodigoInterno")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    b.Property<int>("Guiaenvio")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GUIAENVIO");

                    b.Property<int>("Cantidadenviada")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CANTIDADENVIADA");

                    b.Property<string>("Novedad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("NOVEDAD");

                    b.Property<int?>("Numpedidoesp")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMPEDIDOESP");

                    b.HasKey("CodigoInterno", "Guiaenvio");

                    b.HasIndex("Guiaenvio");

                    b.HasIndex("Numpedidoesp");

                    b.ToTable("PRODUCTOSENVIADOS", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Productovendido", b =>
                {
                    b.Property<int>("CodigoInterno")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    b.Property<int>("Numventa")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMVENTA");

                    b.Property<int>("Cantidadvendida")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CANTIDADVENDIDA");

                    b.HasKey("CodigoInterno", "Numventa");

                    b.HasIndex("Numventa");

                    b.ToTable("PRODUCTOVENDIDO", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Repodetalle", b =>
                {
                    b.Property<int>("CodigoInterno")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    b.Property<int>("Numrepo")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMREPO");

                    b.Property<int>("Cantidad")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CANTIDAD");

                    b.HasKey("CodigoInterno", "Numrepo");

                    b.HasIndex("Numrepo");

                    b.ToTable("REPODETALLES", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Repopedido", b =>
                {
                    b.Property<int>("Numrepo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMREPO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numrepo"));

                    b.Property<int>("Codigosucursal")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOSUCURSAL");

                    b.Property<DateTime>("Fechapedido")
                        .HasColumnType("DATE")
                        .HasColumnName("FECHAPEDIDO");

                    b.HasKey("Numrepo");

                    b.HasIndex("Codigosucursal");

                    b.ToTable("REPOPEDIDO", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Sucursal", b =>
                {
                    b.Property<int>("Codigosucursal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOSUCURSAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigosucursal"));

                    b.Property<string>("Nombresucursal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NOMBRESUCURSAL");

                    b.Property<string>("Telefonosucursal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TELEFONOSUCURSAL");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("UBICACION");

                    b.HasKey("Codigosucursal");

                    b.ToTable("SUCURSAL", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Tarjetaregalo", b =>
                {
                    b.Property<int>("CodigoInterno")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOINTERNO");

                    b.Property<int>("Saldo")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SALDO");

                    b.HasKey("CodigoInterno");

                    b.ToTable("TARJETAREGALO", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Ventum", b =>
                {
                    b.Property<int>("Numventa")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMVENTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numventa"));

                    b.Property<int>("Codigosucursal")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOSUCURSAL");

                    b.Property<DateTime?>("Fechacompra")
                        .HasColumnType("DATE")
                        .HasColumnName("FECHACOMPRA");

                    b.Property<int?>("Total")
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL");

                    b.HasKey("Numventa");

                    b.HasIndex("Codigosucursal");

                    b.ToTable("VENTA", (string)null);
                });

            modelBuilder.Entity("WormBook.Models.Envio", b =>
                {
                    b.HasOne("WormBook.Models.Sucursal", "SucursaldestinoNavigation")
                        .WithMany("EnvioSucursaldestinoNavigations")
                        .HasForeignKey("Sucursaldestino")
                        .IsRequired()
                        .HasConstraintName("FK_ENVIO_SUCURSALDESTINO");

                    b.HasOne("WormBook.Models.Sucursal", "SucursalorigenNavigation")
                        .WithMany("EnvioSucursalorigenNavigations")
                        .HasForeignKey("Sucursalorigen")
                        .IsRequired()
                        .HasConstraintName("FK_ENVIO_SUCURSALORIGEN");

                    b.Navigation("SucursaldestinoNavigation");

                    b.Navigation("SucursalorigenNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Existencium", b =>
                {
                    b.HasOne("WormBook.Models.Producto", "CodigointernoNavigation")
                        .WithMany("Existencia")
                        .HasForeignKey("CodigoInterno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EXISTENCIA_PRODUCTO");

                    b.HasOne("WormBook.Models.Sucursal", "CodigosucursalNavigation")
                        .WithMany("Existencia")
                        .HasForeignKey("Codigosucursal")
                        .IsRequired()
                        .HasConstraintName("FK_EXISTENCIA_SUCURSAL");

                    b.Navigation("CodigointernoNavigation");

                    b.Navigation("CodigosucursalNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Juegomesa", b =>
                {
                    b.HasOne("WormBook.Models.Producto", "CodigointernoNavigation")
                        .WithOne("Juegomesa")
                        .HasForeignKey("WormBook.Models.Juegomesa", "Codigointerno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_JUEGOMESA_PRODUCTO");

                    b.Navigation("CodigointernoNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Libro", b =>
                {
                    b.HasOne("WormBook.Models.Producto", "CodigoInternoNavigation")
                        .WithOne("Libro")
                        .HasForeignKey("WormBook.Models.Libro", "CodigoInterno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LIBRO_PRODUCTO");

                    b.Navigation("CodigoInternoNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Pedidoespecial", b =>
                {
                    b.HasOne("WormBook.Models.Producto", "CodigoInternoNavigation")
                        .WithMany("Pedidoespecials")
                        .HasForeignKey("CodigoInterno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDOESPECIAL_PRODUCTO");

                    b.HasOne("WormBook.Models.Sucursal", "CodigosucursalNavigation")
                        .WithMany("Pedidoespecials")
                        .HasForeignKey("Codigosucursal")
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDOESPECIAL_SUCURSAL");

                    b.HasOne("WormBook.Models.Cliente", "IdclienteNavigation")
                        .WithMany("Pedidoespecials")
                        .HasForeignKey("Idcliente")
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDOESPECIAL_CLIENTE");

                    b.Navigation("CodigoInternoNavigation");

                    b.Navigation("CodigosucursalNavigation");

                    b.Navigation("IdclienteNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Productosenviado", b =>
                {
                    b.HasOne("WormBook.Models.Producto", "CodigoInternoNavigation")
                        .WithMany("Productosenviados")
                        .HasForeignKey("CodigoInterno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTOSENVIADOS_PRODUCTO");

                    b.HasOne("WormBook.Models.Envio", "GuiaenvioNavigation")
                        .WithMany("Productosenviados")
                        .HasForeignKey("Guiaenvio")
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTOSENVIADOS_ENVIO");

                    b.HasOne("WormBook.Models.Pedidoespecial", "NumpedidoespNavigation")
                        .WithMany("Productosenviados")
                        .HasForeignKey("Numpedidoesp")
                        .HasConstraintName("FK_PRODUCTOSENVIADOS_PEDIDOESPECIAL");

                    b.Navigation("CodigoInternoNavigation");

                    b.Navigation("GuiaenvioNavigation");

                    b.Navigation("NumpedidoespNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Productovendido", b =>
                {
                    b.HasOne("WormBook.Models.Producto", "CodigoInternoNavigation")
                        .WithMany("Productovendidos")
                        .HasForeignKey("CodigoInterno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTOVENDIDO_PRODUCTO");

                    b.HasOne("WormBook.Models.Ventum", "NumventaNavigation")
                        .WithMany("Productovendidos")
                        .HasForeignKey("Numventa")
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTOVENDIDO_VENTA");

                    b.Navigation("CodigoInternoNavigation");

                    b.Navigation("NumventaNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Repodetalle", b =>
                {
                    b.HasOne("WormBook.Models.Producto", "CodigoInternoNavigation")
                        .WithMany("Repodetalles")
                        .HasForeignKey("CodigoInterno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REPODETALLES_PRODUCTO");

                    b.HasOne("WormBook.Models.Repopedido", "NumrepoNavigation")
                        .WithMany("Repodetalles")
                        .HasForeignKey("Numrepo")
                        .IsRequired()
                        .HasConstraintName("FK_REPODETALLES_REPOPEDIDO");

                    b.Navigation("CodigoInternoNavigation");

                    b.Navigation("NumrepoNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Repopedido", b =>
                {
                    b.HasOne("WormBook.Models.Sucursal", "CodigosucursalNavigation")
                        .WithMany("Repopedidos")
                        .HasForeignKey("Codigosucursal")
                        .IsRequired()
                        .HasConstraintName("FK_REPOPEDIDO_SUCURSAL");

                    b.Navigation("CodigosucursalNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Tarjetaregalo", b =>
                {
                    b.HasOne("WormBook.Models.Producto", "CodigoInternoNavigation")
                        .WithOne("Tarjetaregalo")
                        .HasForeignKey("WormBook.Models.Tarjetaregalo", "CodigoInterno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TARJETAREGALO_PRODUCTO");

                    b.Navigation("CodigoInternoNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Ventum", b =>
                {
                    b.HasOne("WormBook.Models.Sucursal", "CodigosucursalNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("Codigosucursal")
                        .IsRequired()
                        .HasConstraintName("FK_VENTA_SUCURSAL");

                    b.Navigation("CodigosucursalNavigation");
                });

            modelBuilder.Entity("WormBook.Models.Cliente", b =>
                {
                    b.Navigation("Pedidoespecials");
                });

            modelBuilder.Entity("WormBook.Models.Envio", b =>
                {
                    b.Navigation("Productosenviados");
                });

            modelBuilder.Entity("WormBook.Models.Pedidoespecial", b =>
                {
                    b.Navigation("Productosenviados");
                });

            modelBuilder.Entity("WormBook.Models.Producto", b =>
                {
                    b.Navigation("Existencia");

                    b.Navigation("Juegomesa");

                    b.Navigation("Libro");

                    b.Navigation("Pedidoespecials");

                    b.Navigation("Productosenviados");

                    b.Navigation("Productovendidos");

                    b.Navigation("Repodetalles");

                    b.Navigation("Tarjetaregalo");
                });

            modelBuilder.Entity("WormBook.Models.Repopedido", b =>
                {
                    b.Navigation("Repodetalles");
                });

            modelBuilder.Entity("WormBook.Models.Sucursal", b =>
                {
                    b.Navigation("EnvioSucursaldestinoNavigations");

                    b.Navigation("EnvioSucursalorigenNavigations");

                    b.Navigation("Existencia");

                    b.Navigation("Pedidoespecials");

                    b.Navigation("Repopedidos");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("WormBook.Models.Ventum", b =>
                {
                    b.Navigation("Productovendidos");
                });
#pragma warning restore 612, 618
        }
    }
}
